spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true # jpa? ???? ??? ?? ??? ??

logging:
  level:
    org.hibernate.sql: debug #??? ???? ?? ?? ?? ??? ????